version: '2' 
services:
  
  proxy:
    build: ./nginx
    ports:
      - "3000:3000"
    container_name: balancer

  db:
    image: mongo
    ports:
        - "27017"
    volumes:
      - "/var/mongo-data:/data/db"
    restart: on-failure
    container_name: database
  
  app:
      build:
        context: .
        args:
          NODE_URL: http://icoworld.projects.oktend.com:8545
      ports:
        - "3000"
  backend-1:
    extends:
      service: app
  backend-2:
    extends:
      service: app
