version: '2'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
        - "8081:8081"
    volumes:
      - mongo-data:/var/lib/mongodb

  app:
      build: .
      # image: backend:0.1.1
      ports:
        - "8000:8000"
      depends_on:
        - db
      
volumes:
  mongo-data: {}
