version: '2'

services:
  db:
    image: mongo
    #    environment:
    #      - MONGODB_DATABASE=ico_world_db
    #      - MONGODB_USER=root
    #      - MONGODB_PASSWORD=root
    ports:
        - "27017:27017"
    volumes:
      - "/var/mongo-data:/data/db"
    restart: on-failure 
  
  app:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - "db"
      command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]
