version: '2' 
services:
  db:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
      - "/var/mongo-data:/data/db"
    restart: on-failure 
  
  app:
      build:
        context: .
        args:
          NODE_URL=http://icoworld.projects.oktend.com:8545
      ports:
        - "3000:3000"
      depends_on:
        - "db"
      command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]
