version: '2' 
services:
  
  proxy:
    build: ./nginx
    ports:
      - "3000:3000"
    container_name: balancer

  db:
    image: mongo
    volumes:
      - "/var/mongo-data:/data/db"
      - "/var/mongo-backup:/opt"
    restart: on-failure
    container_name: database
  
  app:
      build:
        context: .
        args:
          NODE_URL: http://icoworld.projects.oktend.com:8545
          ETH_NODE_URL: http://icoworld.projects.oktend.com:8545
          ETH_PRIVATE_KEY: 123
          ETH_FROM_ACCOUNT: "0xf1234b070814a4b834535d5f6cf7d3424ea84e43"
          PORT: 3000
          DB_URI: mongodb://db:27017/ico_world_db
      image: ico/backend:$BUILD_ID
  backend-1:
    extends:
      service: app
  backend-2:
    extends:
      service: app
