version: '2'

services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
        - "27017:27017"
    volumes:
      - "./mongo-data:/var/lib/mongodb"
    restart: always
  app:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - "db"
      command: ["./wait-for-it.sh", "db:27017", "--", "npm", "start"]
      restart: always
